# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=5)),
                ('course_title', models.CharField(max_length=200)),
                ('course_number', models.CharField(max_length=15)),
                ('year', models.PositiveSmallIntegerField()),
                ('term', models.CharField(max_length=6)),
                ('professor', models.CharField(max_length=50)),
                ('max_num_seats', models.PositiveSmallIntegerField()),
                ('filled_num_seats', models.PositiveSmallIntegerField()),
                ('waitlist_seats', models.PositiveSmallIntegerField()),
                ('xlist_seats', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=25)),
                ('cw', models.BooleanField()),
                ('reserved_seats', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pastCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=5)),
                ('course_title', models.CharField(max_length=200)),
                ('course_number', models.CharField(max_length=15)),
                ('year', models.PositiveSmallIntegerField()),
                ('term', models.CharField(max_length=6)),
                ('max_num_seats', models.PositiveSmallIntegerField()),
                ('filled_num_seats', models.PositiveSmallIntegerField()),
                ('waitlist_seats', models.PositiveSmallIntegerField()),
                ('xlist_seats', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
