# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprsite', '0002_auto_20161204_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcourse',
            name='cw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currentcourse',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='currentcourse',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
