# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprsite', '0005_pastcourse_reserved_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastcourse',
            name='professor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
