# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcourse',
            name='cw',
            field=models.BooleanField(default='false'),
        ),
        migrations.AlterField(
            model_name='currentcourse',
            name='filled_num_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='currentcourse',
            name='max_num_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='currentcourse',
            name='reserved_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='currentcourse',
            name='waitlist_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='currentcourse',
            name='xlist_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='currentcourse',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
