# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprsite', '0004_auto_20161204_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastcourse',
            name='reserved_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
