# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprsite', '0006_pastcourse_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastcourse',
            name='cw',
            field=models.BooleanField(default=False),
        ),
    ]
