# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprsite', '0007_pastcourse_cw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastcourse',
            name='reserved_seats',
        ),
    ]
