# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprsite', '0009_auto_20161205_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcourse',
            name='end_time_one',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currentcourse',
            name='end_time_two',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currentcourse',
            name='start_time_one',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currentcourse',
            name='start_time_two',
            field=models.CharField(max_length=10),
        ),
    ]
