# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprsite', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grad_year',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
