# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprsite', '0012_userprofile_grad_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcourse',
            name='num_freshman_febs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='num_freshmen',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='num_junior_febs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='num_juniors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='num_senior_febs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='num_seniors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='num_sophomore_febs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='num_sophomores',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
